## PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([1, 5])
vector

tensor([1, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [1, 4, 9],
        [16, 25, 36],
        [49, 64, 81]
    ]
])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

In [ ]:
rand_image_size_tensor = torch.rand(size=(3, 224, 224))
rand_image_size_tensor.shape, rand_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones:

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Range of Tensors and tensors-like

In [ ]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

## Tensor Datatypes

In [ ]:
tensor_float_32 = torch.tensor([3.0, 4.5, 6.7],
                               dtype=torch.float32, # Data Type
                               device="cpu", # What device is your tensor on
                               requires_grad=False # Whether or not to track the gradients with this tensor operations
                               )
tensor_float_32

tensor([3.0000, 4.5000, 6.7000])

In [ ]:
tensor_float_16 = tensor_float_32.type(torch.float16)
tensor_float_16.dtype

torch.float16

## Manipulating Tensors

In [ ]:
tensor = torch.rand(3)
tensor

tensor([0.9011, 0.6884, 0.4160])

In [ ]:
# Add
tensor + tensor

tensor([1.8021, 1.3768, 0.8320])

In [ ]:
# Sub
tensor - 3

tensor([-2.0989, -2.3116, -2.5840])

In [ ]:
# Mul
tensor * tensor

tensor([0.8119, 0.4739, 0.1731])

In [ ]:
# Div
tensor / tensor

tensor([1., 1., 1.])

In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(1.4589)

## Transpose

In [ ]:
MATRIX = torch.tensor([[1, 2], [3, 4], [5, 6]])
MATRIX, MATRIX.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]))

## Tensor Aggregation

In [ ]:
x = torch.arange(0, 100, 2.5)

In [ ]:
x.min(), x.max(), x.mean(), x.sum()

(tensor(0.), tensor(97.5000), tensor(48.7500), tensor(1950.))

In [ ]:
# Finding the position of the min and the max values
x.argmin(), x.argmax()

(tensor(0), tensor(39))

## Reshaping, Viewing and Stacking

In [ ]:
y = torch.arange(1, 41)
y

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40])

In [ ]:
y_reshaped = y.reshape(10, 4)
y_reshaped

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]])

In [ ]:
z = y.view(4, 10) # It creates a copy of the tensor with a different shape, but sharing the same memory
z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [ ]:
z[:, 0] = 100 # It changes the original tensor 'y'
z, y

(tensor([[100,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [100,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [100,  32,  33,  34,  35,  36,  37,  38,  39,  40]]),
 tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100,  12,  13,  14,
          15,  16,  17,  18,  19,  20, 100,  22,  23,  24,  25,  26,  27,  28,
          29,  30, 100,  32,  33,  34,  35,  36,  37,  38,  39,  40]))

In [ ]:
z_stacked = torch.stack([z, z, z], dim=0)
z_stacked

tensor([[[100,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [100,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [100,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

        [[100,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [100,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [100,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

        [[100,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [100,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [100,  32,  33,  34,  35,  36,  37,  38,  39,  40]]])

In [ ]:
z_stacked = torch.stack([z, z, z], dim=1)
z_stacked

tensor([[[100,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [100,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [100,   2,   3,   4,   5,   6,   7,   8,   9,  10]],

        [[100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [100,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

        [[100,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [100,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [100,  22,  23,  24,  25,  26,  27,  28,  29,  30]],

        [[100,  32,  33,  34,  35,  36,  37,  38,  39,  40],
         [100,  32,  33,  34,  35,  36,  37,  38,  39,  40],
         [100,  32,  33,  34,  35,  36,  37,  38,  39,  40]]])

## Squeezing, Unsqueezing and Permuting

In [ ]:
x = torch.rand(3, 1, 6)
x

tensor([[[0.0123, 0.0421, 0.7335, 0.2395, 0.5177, 0.2525]],

        [[0.1821, 0.8676, 0.6433, 0.5072, 0.7951, 0.6800]],

        [[0.7601, 0.2976, 0.9655, 0.7183, 0.4858, 0.8532]]])

In [ ]:
y = torch.squeeze(x)
y

tensor([[0.0123, 0.0421, 0.7335, 0.2395, 0.5177, 0.2525],
        [0.1821, 0.8676, 0.6433, 0.5072, 0.7951, 0.6800],
        [0.7601, 0.2976, 0.9655, 0.7183, 0.4858, 0.8532]])

In [ ]:
z = torch.unsqueeze(y, dim=0)
z, z.shape

(tensor([[[0.0123, 0.0421, 0.7335, 0.2395, 0.5177, 0.2525],
          [0.1821, 0.8676, 0.6433, 0.5072, 0.7951, 0.6800],
          [0.7601, 0.2976, 0.9655, 0.7183, 0.4858, 0.8532]]]),
 torch.Size([1, 3, 6]))

## PyTorch and NumPy

In [ ]:
numpy_arr = np.arange(1, 20, 2.5)
numpy_arr

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [ ]:
pytorch_tensor = torch.from_numpy(numpy_arr)
pytorch_tensor

tensor([ 1.0000,  3.5000,  6.0000,  8.5000, 11.0000, 13.5000, 16.0000, 18.5000],
       dtype=torch.float64)

In [ ]:
t = torch.arange(0, 200, 20)
t

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [ ]:
ndarr = t.numpy()
ndarr

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [ ]:
!nvidia-smi

Thu Nov  6 19:36:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## GPU access with PyTorch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor_on_cpu = torch.arange(0, 10)
tensor_on_cpu.device

device(type='cpu')

In [ ]:
tensor_on_gpu = tensor_on_cpu.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

In [ ]:
backing_to_cpu = tensor_on_gpu.cpu()
backing_to_cpu.device

device(type='cpu')