# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch

tensor = torch.rand(7, 7)
tensor


tensor([[0.9687, 0.4921, 0.5590, 0.5407, 0.7164, 0.5394, 0.2046],
        [0.4214, 0.1938, 0.4178, 0.6274, 0.3035, 0.9804, 0.6281],
        [0.0117, 0.8598, 0.3583, 0.8323, 0.0393, 0.3170, 0.7152],
        [0.3943, 0.2306, 0.1447, 0.0979, 0.7811, 0.4535, 0.7921],
        [0.2013, 0.7560, 0.3763, 0.5463, 0.0352, 0.1907, 0.3455],
        [0.3414, 0.5150, 0.9040, 0.5608, 0.3404, 0.9459, 0.8234],
        [0.1832, 0.5603, 0.6671, 0.9296, 0.1794, 0.0125, 0.9480]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
tensor_2 = torch.rand(1, 7)
tensor_2_reshaped = tensor_2.reshape(7, 1)

torch.matmul(tensor, tensor_2_reshaped)


tensor([[1.8889],
        [1.8962],
        [1.5650],
        [0.9764],
        [1.2176],
        [2.3623],
        [1.6934]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(1, 7)

tensor_2_reshaped = tensor_2.reshape(7, 1)

result = torch.matmul(tensor_1, tensor_2_reshaped)
result, result.shape




(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
GPU_RANDOM_SEED = 1234
torch.cuda.manual_seed(GPU_RANDOM_SEED) if torch.cuda.is_available() else None



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(GPU_RANDOM_SEED)
x = torch.rand(2, 3, device=device)

torch.manual_seed(GPU_RANDOM_SEED)
y = torch.rand(2, 3, device=device)

device, x, y


('cuda',
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
y = y.reshape(3, 2)
output = torch.matmul(x, y)


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
output.max(), output.min()


(tensor(1.6667, device='cuda:0'), tensor(0.4969, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
output.argmax(), output.argmin()


(tensor(3, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
random_seed = 42

torch.manual_seed(random_seed)
x = torch.rand(1, 1, 1, 10)
print(x, x.shape)

y = x.squeeze()
print(y, y.shape)


tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332]) torch.Size([10])
